version: "3"

services:
    rabbitmq-server:
        image: rabbitmq:3-alpine
        container_name: rabbitmq-server

    api:
        build: ./flask-api/
        container_name: flask-api
        depends_on:
            - rabbitmq-server
        ports:
            - "5000:5000"
